services:
  - type: web
    name: sports-schedulers
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_PATH
        value: /opt/render/project/scheduler.db
    healthCheckPath: /health